/*
  ============================================================
  CONTEÚDO DO SITE — TIME JP
  ============================================================
  Base atualizada com os 51 cartoons fornecidos pela equipe.
  Antes da publicação definitiva, valide nome, função e frase
  com cada pessoa retratada e altere modoDemonstracao para false.
  ============================================================
*/

const SITE_CONFIG = {
  modoDemonstracao: true,
  ultimaAtualizacao: "17/09/2026",
};

const ESCOLA_INFO = {
  chamada: "QUEM FAZ O JARBAS ACONTECER",
  mensagemTopo: "O conhecimento que transforma o seu presente e constrói o seu amanhã.",
  nomeEscola: "EEFM Dr. Jarbas Passarinho",
  assinatura: "Heróis que fazem a escola acontecer",
  historia: "Uma homenagem a quem ensina, acolhe, organiza, cuida e mantém a escola em movimento todos os dias.",
  estatisticas: [
    { numero: "51", legenda: "cartoons individuais atualizados" },
  ],
};

const CATEGORIAS = [
  { id: "todos",             nome: "TODOS",                 cor: "#111111", texto: "#FFFFFF" },
  { id: "professores",       nome: "PROFESSORES",           cor: "#E63946", texto: "#FFFFFF" },
  { id: "coordenacao",       nome: "COORDENAÇÃO",           cor: "#1D3557", texto: "#FFFFFF" },
  { id: "direcao",           nome: "DIREÇÃO",               cor: "#8E44AD", texto: "#FFFFFF" },
  { id: "educacao_especial", nome: "EDUCAÇÃO ESPECIAL",     cor: "#2A9D8F", texto: "#FFFFFF" },
  { id: "educacao_infantil", nome: "EDUCAÇÃO INFANTIL",     cor: "#F4A300", texto: "#111111" },
  { id: "apoio",             nome: "APOIO / PORTARIA",      cor: "#006D77", texto: "#FFFFFF" },
  { id: "secretaria",        nome: "SECRETARIA",            cor: "#457B9D", texto: "#FFFFFF" },
  { id: "psicologia",        nome: "PSICOLOGIA",            cor: "#6C757D", texto: "#FFFFFF" },
];

function ficha({
  id,
  nome,
  nomeHeroico,
  funcao,
  categoria,
  setor,
  contribuicao,
  frase,
  foto,
  origemArquivo,
}) {
  return {
    id,
    nome,
    nomeHeroico,
    funcao,
    categoria,
    setor,
    contribuicao,
    frase,
    foto,
    textoAlternativo: `Ilustração em estilo cartoon de ${nome}, ${funcao}.`,
    origemArquivo,
  };
}

function docente({
  id,
  nome,
  disciplina,
  nomeHeroico,
  contribuicao,
  frase,
  arquivo,
}) {
  return ficha({
    id,
    nome,
    nomeHeroico,
    funcao: `Professor(a) de ${disciplina}`,
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao,
    frase,
    foto: `img/equipe/professores/${arquivo}`,
    origemArquivo: `Professores/${arquivo}`,
  });
}

const EQUIPE = [
  ficha({
    id: "cartoon-001",
    nome: "Silvia",
    nomeHeroico: "Liderança na escola",
    funcao: "Diretora",
    categoria: "direcao",
    setor: "Direção",
    contribuicao: "Orienta decisões e caminhos para a escola avançar.",
    frase: "Conduz a escola com escuta, presença e compromisso com cada aprendizagem.",
    foto: "img/equipe/direcao/Diretora - Silvia.png",
    origemArquivo: "Direção/Diretora - Silvia.png",
  }),
  ficha({
    id: "cartoon-002",
    nome: "Adriano",
    nomeHeroico: "Liderança na escola",
    funcao: "Vice-diretor",
    categoria: "direcao",
    setor: "Direção",
    contribuicao: "Articula pessoas, rotinas e soluções para o cotidiano escolar.",
    frase: "Transforma organização em apoio para que a escola siga em movimento.",
    foto: "img/equipe/direcao/Vice diretor - Adriano.png",
    origemArquivo: "Direção/Vice diretor - Adriano.png",
  }),
  ficha({
    id: "cartoon-003",
    nome: "Cinthya Guerra",
    nomeHeroico: "Pontes pedagógicas",
    funcao: "Coordenação Pedagógica",
    categoria: "coordenacao",
    setor: "Coordenação",
    contribuicao: "Acompanha processos pedagógicos e fortalece o trabalho docente.",
    frase: "Aproxima planejamento, acompanhamento e aprendizagem em cada etapa do caminho.",
    foto: "img/equipe/coordenacao/Coordenação - Cinthya Guerra.png",
    origemArquivo: "Coodenação/Coordenação - Cinthya Guerra.png",
  }),
  ficha({
    id: "cartoon-004",
    nome: "Elaine",
    nomeHeroico: "Pontes pedagógicas",
    funcao: "Coordenação Pedagógica",
    categoria: "coordenacao",
    setor: "Coordenação",
    contribuicao: "Conecta planejamento, acompanhamento e diálogo pedagógico.",
    frase: "Fortalece o percurso de quem ensina e de quem aprende todos os dias.",
    foto: "img/equipe/coordenacao/Coordenação - Elaine.png",
    origemArquivo: "Coodenação/Coordenação - Elaine.png",
  }),
  ficha({
    id: "cartoon-005",
    nome: "Nadja",
    nomeHeroico: "Inclusão em ação",
    funcao: "Educação Especial",
    categoria: "educacao_especial",
    setor: "Educação Especial",
    contribuicao: "Fortalece a inclusão e o acompanhamento dos estudantes.",
    frase: "Abre caminhos para que cada estudante participe, aprenda e seja reconhecido.",
    foto: "img/equipe/educacao-especial/Educação especial - Nadja.png",
    origemArquivo: "Educação especial/Educação especial - Nadja.png",
  }),
  ficha({
    id: "cartoon-006",
    nome: "Degiane",
    nomeHeroico: "Inclusão em ação",
    funcao: "Educação Especial",
    categoria: "educacao_especial",
    setor: "Educação Especial",
    contribuicao: "Constrói estratégias de apoio para ampliar a participação escolar.",
    frase: "Transforma acolhimento e planejamento em oportunidades reais de aprendizagem.",
    foto: "img/equipe/educacao-especial/Educação Especial -Degiane.png",
    origemArquivo: "Educação especial/Educação Especial -Degiane.png",
  }),
  ficha({
    id: "cartoon-007",
    nome: "Silvio",
    nomeHeroico: "Primeiros passos, grandes descobertas",
    funcao: "Educação Infantil",
    categoria: "educacao_infantil",
    setor: "Educação Infantil",
    contribuicao: "Cuida das experiências que iniciam a trajetória de aprendizagem.",
    frase: "Faz da curiosidade infantil uma porta aberta para descobrir o mundo.",
    foto: "img/equipe/educacao-infantil/Educação Infantil - Silvio.png",
    origemArquivo: "Educação Infantil/Educação Infantil - Silvio.png",
  }),
  ficha({
    id: "cartoon-008",
    nome: "Seu Eduardo",
    nomeHeroico: "Cuidado na chegada",
    funcao: "Portaria",
    categoria: "apoio",
    setor: "Portaria",
    contribuicao: "Acolhe, orienta e contribui para uma rotina escolar segura.",
    frase: "Faz da porta da escola um lugar de respeito, atenção e boas-vindas.",
    foto: "img/equipe/portaria/Seu Eduardo.png",
    origemArquivo: "Portaria/Seu Eduardo.png",
  }),
  ficha({
    id: "cartoon-009",
    nome: "Arlindo",
    nomeHeroico: "Apoio que faz acontecer",
    funcao: "Apoio à Gestão",
    categoria: "apoio",
    setor: "Apoio à Gestão",
    contribuicao: "Colabora com a organização e o funcionamento diário da escola.",
    frase: "Mostra que cada cuidado com a rotina também educa e faz a escola avançar.",
    foto: "img/equipe/apoio/Arlindo.png",
    origemArquivo: "Apoio a Gestão/Arlindo.png",
  }),
  ficha({
    id: "cartoon-010",
    nome: "Camila",
    nomeHeroico: "Apoio que faz acontecer",
    funcao: "Apoio à Gestão",
    categoria: "apoio",
    setor: "Apoio à Gestão",
    contribuicao: "Contribui para que os espaços e as rotinas escolares funcionem bem.",
    frase: "Transforma atenção aos detalhes em acolhimento para toda a comunidade escolar.",
    foto: "img/equipe/apoio/Camila.png",
    origemArquivo: "Apoio a Gestão/Camila.png",
  }),
  ficha({
    id: "cartoon-011",
    nome: "Cley",
    nomeHeroico: "Apoio que faz acontecer",
    funcao: "Apoio à Gestão",
    categoria: "apoio",
    setor: "Apoio à Gestão",
    contribuicao: "Sustenta atividades que mantêm o cotidiano escolar em movimento.",
    frase: "Sua presença transforma necessidades diárias em soluções para a escola.",
    foto: "img/equipe/apoio/Cley.png",
    origemArquivo: "Apoio a Gestão/Cley.png",
  }),
  ficha({
    id: "cartoon-012",
    nome: "Eliza",
    nomeHeroico: "Apoio que faz acontecer",
    funcao: "Apoio à Gestão",
    categoria: "apoio",
    setor: "Apoio à Gestão",
    contribuicao: "Ajuda a organizar os bastidores que sustentam a vida escolar.",
    frase: "Cuida do que muitas vezes não aparece, mas faz toda a diferença no dia a dia.",
    foto: "img/equipe/apoio/Eliza.png",
    origemArquivo: "Apoio a Gestão/Eliza.png",
  }),
  ficha({
    id: "cartoon-013",
    nome: "Joilton",
    nomeHeroico: "Apoio que faz acontecer",
    funcao: "Apoio à Gestão",
    categoria: "apoio",
    setor: "Apoio à Gestão",
    contribuicao: "Contribui com agilidade e presença para a rotina escolar.",
    frase: "Faz do trabalho coletivo uma força concreta para a escola funcionar melhor.",
    foto: "img/equipe/apoio/Joilton.png",
    origemArquivo: "Apoio a Gestão/Joilton.png",
  }),
  ficha({
    id: "cartoon-014",
    nome: "Simone",
    nomeHeroico: "Apoio que faz acontecer",
    funcao: "Apoio à Gestão",
    categoria: "apoio",
    setor: "Apoio à Gestão",
    contribuicao: "Apoia a organização dos serviços que atendem a comunidade escolar.",
    frase: "Contribui com dedicação para que todos encontrem uma escola mais acolhedora.",
    foto: "img/equipe/apoio/Simone.png",
    origemArquivo: "Apoio a Gestão/Simone.png",
  }),
  ficha({
    id: "cartoon-015",
    nome: "Rochinha",
    nomeHeroico: "Organização que conecta",
    funcao: "Secretaria",
    categoria: "secretaria",
    setor: "Secretaria Escolar",
    contribuicao: "Apoia os registros e os atendimentos que conectam escola e comunidade.",
    frase: "Transforma informação bem cuidada em segurança para as rotinas da escola.",
    foto: "img/equipe/secretaria/Secretaria - Rochinha.png",
    origemArquivo: "Secretaria/Secretaria - Rochinha.png",
  }),
  ficha({
    id: "cartoon-016",
    nome: "Rilze",
    nomeHeroico: "Organização que conecta",
    funcao: "Secretaria",
    categoria: "secretaria",
    setor: "Secretaria Escolar",
    contribuicao: "Contribui para o atendimento e a organização das informações escolares.",
    frase: "Dá forma aos processos que ajudam a escola a dialogar com todos.",
    foto: "img/equipe/secretaria/Secretaria Rilze.png",
    origemArquivo: "Secretaria/Secretaria Rilze.png",
  }),
  ficha({
    id: "cartoon-017",
    nome: "Giselle",
    nomeHeroico: "Organização que conecta",
    funcao: "Secretária",
    categoria: "secretaria",
    setor: "Secretaria Escolar",
    contribuicao: "Organiza informações e acolhe demandas da comunidade escolar.",
    frase: "Faz da escuta e da precisão um apoio essencial para a vida da escola.",
    foto: "img/equipe/secretaria/Secretária Giselle.png",
    origemArquivo: "Secretaria/Secretária Giselle.png",
  }),
  ficha({
    id: "cartoon-018",
    nome: "Jessica",
    nomeHeroico: "Organização que conecta",
    funcao: "Secretária",
    categoria: "secretaria",
    setor: "Secretaria Escolar",
    contribuicao: "Apoia procedimentos que tornam o atendimento escolar mais claro.",
    frase: "Constrói pontes entre pessoas, documentos e necessidades do cotidiano.",
    foto: "img/equipe/secretaria/Secretária Jessica.png",
    origemArquivo: "Secretaria/Secretária Jessica.png",
  }),
  ficha({
    id: "cartoon-019",
    nome: "Virgílhio",
    nomeHeroico: "Escuta que acolhe",
    funcao: "Psicólogo",
    categoria: "psicologia",
    setor: "Psicologia Escolar",
    contribuicao: "Favorece espaços de escuta, cuidado e bem-estar na escola.",
    frase: "Valoriza cada diálogo como possibilidade de fortalecer vínculos e trajetórias.",
    foto: "img/equipe/psicologia/Psicólogo Virgílhio_.png",
    origemArquivo: "Psicólogo/Psicólogo Virgílhio_.png",
  }),
  ficha({
    id: "cartoon-020",
    nome: "Equipe Terceirizada",
    nomeHeroico: "Cuidado com os espaços",
    funcao: "Serviços Terceirizados",
    categoria: "apoio",
    setor: "Serviços Terceirizados",
    contribuicao: "Contribui para a conservação e o cuidado dos espaços da escola.",
    frase: "Ajuda a manter o ambiente escolar pronto para receber quem aprende e ensina.",
    foto: "img/equipe/terceirizada/1789147615252.png",
    origemArquivo: "Terceirizada/1789147615252.png",
  }),
  docente({
    id: "cartoon-021", nome: "Prof. Abel", disciplina: "Educação Física", nomeHeroico: "Movimento em ação",
    contribuicao: "Promove experiências de movimento, saúde e cooperação.",
    frase: "Inspira os estudantes a descobrirem no corpo novas formas de aprender e conviver.",
    arquivo: "Prof. Abel - Educação Física.png",
  }),
  docente({
    id: "cartoon-022", nome: "Prof. Ady", disciplina: "História", nomeHeroico: "História em ação",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Investiga o passado para ajudar os estudantes a compreenderem o presente.",
    arquivo: "Prof. Ady - História.png",
  }),
  docente({
    id: "cartoon-023", nome: "Prof. André", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Fortalece leitura e escrita como ferramentas de expressão e participação.",
    arquivo: "Prof. André - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-024", nome: "Prof. Andréia", disciplina: "História", nomeHeroico: "História em ação",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Transforma o estudo da História em diálogo entre tempos, memórias e experiências.",
    arquivo: "Prof. Andréia - História.png",
  }),
  docente({
    id: "cartoon-025", nome: "Prof. Ane", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Acompanha cada palavra para que os estudantes encontrem a própria voz.",
    arquivo: "Prof. Ane - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-026", nome: "Prof. Aparecida", disciplina: "Inglês", nomeHeroico: "Inglês em ação",
    contribuicao: "Contribui para a aprendizagem na área de Inglês.",
    frase: "Abre janelas para novas culturas por meio da língua inglesa.",
    arquivo: "Prof. Aparecida - Inglês.png",
  }),
  docente({
    id: "cartoon-027", nome: "Prof. Cavalcante", disciplina: "Geografia", nomeHeroico: "Territórios em leitura",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Lê paisagens, territórios e relações humanas para orientar descobertas.",
    arquivo: "Prof. Cavalcante - Geografia.png",
  }),
  docente({
    id: "cartoon-028", nome: "Prof. Cinthia Bello", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Cultiva leitores atentos e autores capazes de comunicar suas ideias.",
    arquivo: "Prof. Cinthia Bello - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-029", nome: "Prof. Cláudia Virginia", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Transforma textos e conversas em oportunidades para ampliar repertórios.",
    arquivo: "Prof. Cláudia Virginia - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-030", nome: "Prof. Cláudia Galvão", disciplina: "Matemática", nomeHeroico: "Matemática em ação",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Mostra que a Matemática organiza perguntas, estratégias e soluções para a vida.",
    arquivo: "Prof. Cláudia galvão - Matemática.png",
  }),
  docente({
    id: "cartoon-031", nome: "Prof. Dantas", disciplina: "Matemática", nomeHeroico: "Matemática em ação",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Convida a turma a transformar desafios em raciocínio, argumento e descoberta.",
    arquivo: "Prof. Dantas - Matemática.png",
  }),
  docente({
    id: "cartoon-032", nome: "Prof. Edir", disciplina: "Artes", nomeHeroico: "Arte que expressa",
    contribuicao: "Contribui para a aprendizagem na área de Artes.",
    frase: "Abre espaço para criar, perceber e comunicar ideias com sensibilidade.",
    arquivo: "Prof. Edir - Artes.png",
  }),
  docente({
    id: "cartoon-033", nome: "Prof. Fernando", disciplina: "Educação Física", nomeHeroico: "Movimento em ação",
    contribuicao: "Promove experiências de movimento, saúde e convivência.",
    frase: "Transforma o jogo em aprendizado sobre respeito, cooperação e superação.",
    arquivo: "Prof. Fernando - Ed. Física.png",
  }),
  docente({
    id: "cartoon-034", nome: "Prof. Fábio", disciplina: "Inglês", nomeHeroico: "Inglês em ação",
    contribuicao: "Contribui para a aprendizagem na área de Inglês.",
    frase: "Conecta palavras, culturas e possibilidades de comunicação com o mundo.",
    arquivo: "Prof. Fábio - Inglês.png",
  }),
  docente({
    id: "cartoon-035", nome: "Prof. Helder", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Faz da linguagem um território de pensamento, autoria e participação.",
    arquivo: "Prof. Helder - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-036", nome: "Prof. Jack", disciplina: "Química", nomeHeroico: "Química em transformação",
    contribuicao: "Contribui para a aprendizagem na área de Química.",
    frase: "Revela como as transformações da matéria ajudam a explicar a vida cotidiana.",
    arquivo: "Prof. Jack - Química.png",
  }),
  docente({
    id: "cartoon-037", nome: "Prof. Jardel", disciplina: "Geografia", nomeHeroico: "Territórios em leitura",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Ajuda a compreender como pessoas, lugares e paisagens contam histórias.",
    arquivo: "Prof. Jardel - Geografia.png",
  }),
  docente({
    id: "cartoon-038", nome: "Prof. Juliana", disciplina: "Matemática", nomeHeroico: "Matemática em ação",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Incentiva a confiança para investigar números, relações e diferentes estratégias.",
    arquivo: "Prof. Juliana - Matemática.png",
  }),
  docente({
    id: "cartoon-039", nome: "Prof. Júlia", disciplina: "Artes", nomeHeroico: "Arte que expressa",
    contribuicao: "Contribui para a aprendizagem na área de Artes.",
    frase: "Desperta olhares criativos para que cada estudante encontre novas formas de se expressar.",
    arquivo: "Prof. Júlia - Artes.png",
  }),
  docente({
    id: "cartoon-040", nome: "Prof. Karla", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Valoriza a palavra como encontro entre leitura, escuta e criação.",
    arquivo: "Prof. Karla - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-041", nome: "Prof. Lene", disciplina: "Filosofia", nomeHeroico: "Filosofia em diálogo",
    contribuicao: "Contribui para a aprendizagem na área de Filosofia.",
    frase: "Cultiva perguntas que ajudam a pensar com autonomia sobre a vida e o mundo.",
    arquivo: "Prof. Lene - Filosofia.png",
  }),
  docente({
    id: "cartoon-042", nome: "Prof. Leodiceia", disciplina: "Estudo Religioso", nomeHeroico: "Diálogo e valores",
    contribuicao: "Contribui para a aprendizagem na área de Estudo Religioso.",
    frase: "Promove respeito às diferenças e reflexões sobre convivência e valores.",
    arquivo: "Prof. Leodiceia - Estudo Religioso.png",
  }),
  docente({
    id: "cartoon-043", nome: "Prof. Marcus", disciplina: "Geografia", nomeHeroico: "Territórios em leitura",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Convida a observar o espaço geográfico como construção viva das sociedades.",
    arquivo: "Prof. Marcus - Geografia.png",
  }),
  docente({
    id: "cartoon-044", nome: "Prof. Marlucia", disciplina: "Língua Portuguesa", nomeHeroico: "Palavras em movimento",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Aproxima literatura, leitura e escrita das experiências dos estudantes.",
    arquivo: "Prof. Marlucia - Língua Portuguesa.png",
  }),
  docente({
    id: "cartoon-045", nome: "Prof. Ozias", disciplina: "Sociologia", nomeHeroico: "Sociedade em análise",
    contribuicao: "Contribui para a aprendizagem na área de Sociologia.",
    frase: "Estimula o olhar crítico para compreender relações, culturas e transformações sociais.",
    arquivo: "Prof. Ozias - Sociologia.png",
  }),
  docente({
    id: "cartoon-046", nome: "Prof. Reinaldo", disciplina: "Matemática", nomeHeroico: "Matemática em ação",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Transforma problemas em investigações e estratégias em conhecimento para a vida.",
    arquivo: "Prof. Reinaldo - Matemática.png",
  }),
  docente({
    id: "cartoon-047", nome: "Prof. Roberto", disciplina: "Geografia", nomeHeroico: "Territórios em leitura",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Relaciona mapas, paisagens e vivências para ampliar a leitura do mundo.",
    arquivo: "Prof. Roberto - Geografia.png",
  }),
  docente({
    id: "cartoon-048", nome: "Prof. Roberto Cunha", disciplina: "Matemática", nomeHeroico: "Matemática em ação",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Demonstra que raciocinar, testar e justificar são caminhos para aprender melhor.",
    arquivo: "Prof. Roberto Cunha - Matemática.png",
  }),
  docente({
    id: "cartoon-049", nome: "Prof. Said", disciplina: "Física", nomeHeroico: "Física em descoberta",
    contribuicao: "Contribui para a aprendizagem na área de Física.",
    frase: "Ajuda a transformar fenômenos do cotidiano em perguntas, hipóteses e explicações.",
    arquivo: "Prof. Said - Física.png",
  }),
  docente({
    id: "cartoon-050", nome: "Prof. Teresinha", disciplina: "Biologia", nomeHeroico: "Biologia em vida",
    contribuicao: "Contribui para a aprendizagem na área de Biologia.",
    frase: "Aproxima ciência e vida para despertar cuidado, curiosidade e responsabilidade.",
    arquivo: "Prof. Teresinha - Biologia.png",
  }),
  docente({
    id: "cartoon-051", nome: "Prof. Valter", disciplina: "Matemática", nomeHeroico: "Matemática em ação",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Estimula a persistência para que cada desafio numérico se torne uma nova possibilidade.",
    arquivo: "Prof. Valter - Matemática.png",
  }),
];
