/*
  ============================================================
  CONTEÚDO DO SITE — TIME JP
  ============================================================
  Esta versão está em HOMOLOGAÇÃO INTERNA. As ilustrações abaixo
  foram importadas dos pacotes recebidos por departamento.

  Antes da publicação de qualquer ficha:
  1. confirme a nomenclatura oficial da escola;
  2. confira a imagem com a pessoa retratada;
  3. valide nome, função, departamento, contribuição e frase;
  4. registre a aprovação final da ficha;
  5. altere modoDemonstracao para false somente após a conferência final.

  CATEGORIAS DISPONÍVEIS:
  professores | coordenacao | direcao | educacao_especial |
  copa | apoio | secretaria | outros
  ============================================================
*/

const SITE_CONFIG = {
  modoDemonstracao: true,
  ultimaAtualizacao: "16/09/2026",
};

const ESCOLA_INFO = {
  chamada: "QUEM FAZ O JARBAS ACONTECER",
  nomeEscola: "EEFM Dr. Jarbas Passarinho",
  assinatura: "Heróis que fazem a escola acontecer",
  historia: "Uma homenagem a quem ensina, acolhe, organiza, cuida e mantém a escola em movimento todos os dias.",
  estatisticas: [
    { numero: "48", legenda: "cartoons individuais importados" },
  ],
};

const CATEGORIAS = [
  { id: "todos",             nome: "TODOS",              cor: "#111111" },
  { id: "professores",       nome: "PROFESSORES",        cor: "#E63946" },
  { id: "coordenacao",       nome: "COORDENAÇÃO",        cor: "#1D3557" },
  { id: "direcao",           nome: "DIREÇÃO",            cor: "#8E44AD" },
  { id: "educacao_especial", nome: "EDUCAÇÃO ESPECIAL",  cor: "#2A9D8F" },
  { id: "copa",              nome: "COPA / COZINHA",     cor: "#F4A300" },
  { id: "apoio",             nome: "APOIO / PORTARIA",   cor: "#2A9D8F" },
  { id: "secretaria",        nome: "SECRETARIA",         cor: "#457B9D" },
  { id: "outros",            nome: "OUTROS",             cor: "#6C757D" },
];

const EQUIPE = [
  {
    id: "cartoon-001",
    nome: "Silvia",
    nomeHeroico: "Liderança na escola",
    funcao: "Diretora",
    categoria: "direcao",
    setor: "Direção",
    contribuicao: "Organiza decisões e caminhos para a escola avançar.",
    frase: "Transforma decisões em caminhos que fortalecem a aprendizagem e a vida escolar.",
    foto: "img/equipe/direcao/Diretora - Silvia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Silvia, Diretora.",
    origemArquivo: "Direção/Diretora - Silvia.png",
  },
  {
    id: "cartoon-002",
    nome: "Adriano",
    nomeHeroico: "Liderança na escola",
    funcao: "Vice-diretor",
    categoria: "direcao",
    setor: "Direção",
    contribuicao: "Organiza decisões e caminhos para a escola avançar.",
    frase: "Articula pessoas e rotinas para que cada dia de escola avance com organização.",
    foto: "img/equipe/direcao/Vice diretor - Adriano.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Adriano, Vice-diretor.",
    origemArquivo: "Direção/Vice diretor - Adriano.png",
  },
  {
    id: "cartoon-003",
    nome: "Nadja",
    nomeHeroico: "Inclusão em ação",
    funcao: "Educação Especial",
    categoria: "educacao_especial",
    setor: "Educação Especial",
    contribuicao: "Fortalece a inclusão e o acompanhamento dos estudantes.",
    frase: "Abre caminhos para que cada estudante participe, aprenda e seja reconhecido.",
    foto: "img/equipe/educacao-especial/Educação especial - Nadja.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Nadja, Educação Especial.",
    origemArquivo: "Educação especial/Educação especial - Nadja.png",
  },
  {
    id: "cartoon-004",
    nome: "Degiane",
    nomeHeroico: "Inclusão em ação",
    funcao: "Educação Especial",
    categoria: "educacao_especial",
    setor: "Educação Especial",
    contribuicao: "Fortalece a inclusão e o acompanhamento dos estudantes.",
    frase: "Conecta apoio, escuta e estratégias para tornar a inclusão uma prática diária.",
    foto: "img/equipe/educacao-especial/Educação Especial -Degiane.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Degiane, Educação Especial.",
    origemArquivo: "Educação especial/Educação Especial -Degiane.png",
  },
  {
    id: "cartoon-005",
    nome: "Prof. Ady",
    nomeHeroico: "História em ação",
    funcao: "Professor(a) de História",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Investiga o passado para ajudar os estudantes a compreenderem o presente.",
    foto: "img/equipe/professores/Prof. Ady - História.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Ady, Professor(a) de História.",
    origemArquivo: "Professores/Prof. Ady - História.png",
  },
  {
    id: "cartoon-006",
    nome: "Prof. Andreia",
    nomeHeroico: "História em ação",
    funcao: "Professor(a) de História",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Liga memórias, acontecimentos e perguntas que ampliam a leitura do mundo.",
    foto: "img/equipe/professores/Prof. Andreia - História.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Andreia, Professor(a) de História.",
    origemArquivo: "Professores/Prof. Andreia - História.png",
  },
  {
    id: "cartoon-007",
    nome: "Prof. André",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Fortalece a leitura e a escrita como ferramentas de expressão e participação.",
    foto: "img/equipe/professores/Prof. André - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. André, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. André - Língua Portuguesa.png",
  },
  {
    id: "cartoon-008",
    nome: "Prof. Andréia",
    nomeHeroico: "História em ação",
    funcao: "Professor(a) de História",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Transforma o estudo da História em diálogo entre diferentes tempos e experiências.",
    foto: "img/equipe/professores/Prof. Andréia - História(1).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Andréia, Professor(a) de História.",
    origemArquivo: "Professores/Prof. Andréia - História(1).png",
  },
  {
    id: "cartoon-009",
    nome: "Prof. Andréia",
    nomeHeroico: "História em ação",
    funcao: "Professor(a) de História",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Desperta perguntas sobre o passado para formar olhares críticos sobre o presente.",
    foto: "img/equipe/professores/Prof. Andréia - História(2).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Andréia, Professor(a) de História.",
    origemArquivo: "Professores/Prof. Andréia - História(2).png",
  },
  {
    id: "cartoon-010",
    nome: "Prof. Andréia",
    nomeHeroico: "História em ação",
    funcao: "Professor(a) de História",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de História.",
    frase: "Valoriza a memória e a pesquisa para dar sentido às histórias que construímos.",
    foto: "img/equipe/professores/Prof. Andréia - História.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Andréia, Professor(a) de História.",
    origemArquivo: "Professores/Prof. Andréia - História.png",
  },
  {
    id: "cartoon-011",
    nome: "Prof. Ane",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Acompanha cada palavra para que os estudantes encontrem sua própria voz.",
    foto: "img/equipe/professores/Prof. Ane - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Ane, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. Ane - Língua Portuguesa.png",
  },
  {
    id: "cartoon-012",
    nome: "Prof. Aparecida",
    nomeHeroico: "Inglês em ação",
    funcao: "Professor(a) de Inglês",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Inglês.",
    frase: "Abre janelas para novas culturas por meio da língua inglesa.",
    foto: "img/equipe/professores/Prof. Aparecida - Inglês.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Aparecida, Professor(a) de Inglês.",
    origemArquivo: "Professores/Prof. Aparecida - Inglês.png",
  },
  {
    id: "cartoon-013",
    nome: "Prof. Cavalcante",
    nomeHeroico: "Geografia em ação",
    funcao: "Professor(a) de Geografia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Lê territórios, paisagens e relações humanas para orientar novas descobertas.",
    foto: "img/equipe/professores/Prof. Cavalcante - Geografia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Cavalcante, Professor(a) de Geografia.",
    origemArquivo: "Professores/Prof. Cavalcante - Geografia.png",
  },
  {
    id: "cartoon-014",
    nome: "Prof. Cinthia Bello",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Cultiva leitores atentos e autores capazes de comunicar suas ideias.",
    foto: "img/equipe/professores/Prof. Cinthia Bello - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Cinthia Bello, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. Cinthia Bello - Língua Portuguesa.png",
  },
  {
    id: "cartoon-015",
    nome: "Prof. Cláudia galvão",
    nomeHeroico: "Matemática em ação",
    funcao: "Professor(a) de Matemática",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Mostra que a Matemática organiza perguntas, estratégias e soluções para a vida.",
    foto: "img/equipe/professores/Prof. Cláudia galvão - Matemática.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Cláudia galvão, Professor(a) de Matemática.",
    origemArquivo: "Professores/Prof. Cláudia galvão - Matemática.png",
  },
  {
    id: "cartoon-016",
    nome: "Prof. Cláudia Virginia",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Incentiva a comunicação clara e o pensamento crítico em cada texto.",
    foto: "img/equipe/professores/Prof. Cláudia Virginia - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Cláudia Virginia, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. Cláudia Virginia - Língua Portuguesa.png",
  },
  {
    id: "cartoon-017",
    nome: "Prof. Dantas",
    nomeHeroico: "Matemática em ação",
    funcao: "Professor(a) de Matemática",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Conecta números e situações reais para transformar raciocínio em escolha.",
    foto: "img/equipe/professores/Prof. Dantas - Matemática.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Dantas, Professor(a) de Matemática.",
    origemArquivo: "Professores/Prof. Dantas - Matemática.png",
  },
  {
    id: "cartoon-018",
    nome: "Prof. Edir",
    nomeHeroico: "Artes em ação",
    funcao: "Professor(a) de Artes",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Artes.",
    frase: "Converte imaginação em linguagem artística e espaço para novas perspectivas.",
    foto: "img/equipe/professores/Prof. Edir - Artes.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Edir, Professor(a) de Artes.",
    origemArquivo: "Professores/Prof. Edir - Artes.png",
  },
  {
    id: "cartoon-019",
    nome: "Prof. Elder",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Fortalece a palavra como ponte entre conhecimento, identidade e convivência.",
    foto: "img/equipe/professores/Prof. Elder - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Elder, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. Elder - Língua Portuguesa.png",
  },
  {
    id: "cartoon-020",
    nome: "Prof. Fernando",
    nomeHeroico: "Ed. Física em ação",
    funcao: "Professor(a) de Ed. Física",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Ed. Física.",
    frase: "Movimenta o corpo, o respeito e a cooperação em cada experiência.",
    foto: "img/equipe/professores/Prof. Fernando - Ed. Física.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Fernando, Professor(a) de Ed. Física.",
    origemArquivo: "Professores/Prof. Fernando - Ed. Física.png",
  },
  {
    id: "cartoon-021",
    nome: "Prof. Fábio",
    nomeHeroico: "Inglês em ação",
    funcao: "Professor(a) de Inglês",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Inglês.",
    frase: "Estimula a curiosidade por idiomas e aproxima estudantes de outros mundos.",
    foto: "img/equipe/professores/Prof. Fábio - Inglês.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Fábio, Professor(a) de Inglês.",
    origemArquivo: "Professores/Prof. Fábio - Inglês.png",
  },
  {
    id: "cartoon-022",
    nome: "Prof. Jack",
    nomeHeroico: "Física em ação",
    funcao: "Professor(a) de Física",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Física.",
    frase: "Investiga forças e movimentos para revelar a lógica presente em cada fenômeno.",
    foto: "img/equipe/professores/Prof. Jack - Física(1).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Jack, Professor(a) de Física.",
    origemArquivo: "Professores/Prof. Jack - Física(1).png",
  },
  {
    id: "cartoon-023",
    nome: "Prof. Jack",
    nomeHeroico: "Física em ação",
    funcao: "Professor(a) de Física",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Física.",
    frase: "Transforma perguntas sobre o universo em experiências de investigação e descoberta.",
    foto: "img/equipe/professores/Prof. Jack - Física.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Jack, Professor(a) de Física.",
    origemArquivo: "Professores/Prof. Jack - Física.png",
  },
  {
    id: "cartoon-024",
    nome: "Prof. Jardel",
    nomeHeroico: "Geografia em ação",
    funcao: "Professor(a) de Geografia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Ajuda a perceber como lugares, pessoas e escolhas transformam o planeta.",
    foto: "img/equipe/professores/Prof. Jardel - Geografia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Jardel, Professor(a) de Geografia.",
    origemArquivo: "Professores/Prof. Jardel - Geografia.png",
  },
  {
    id: "cartoon-025",
    nome: "Prof. Juliana",
    nomeHeroico: "Matemática em ação",
    funcao: "Professor(a) de Matemática",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Desenvolve estratégias matemáticas para enfrentar desafios com autonomia.",
    foto: "img/equipe/professores/Prof. Juliana - Matemática.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Juliana, Professor(a) de Matemática.",
    origemArquivo: "Professores/Prof. Juliana - Matemática.png",
  },
  {
    id: "cartoon-026",
    nome: "Prof. Júlia",
    nomeHeroico: "Artes em ação",
    funcao: "Professor(a) de Artes",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Artes.",
    frase: "Encontra na arte um caminho para experimentar, criar e compartilhar sentidos.",
    foto: "img/equipe/professores/Prof. Júlia - Artes(1).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Júlia, Professor(a) de Artes.",
    origemArquivo: "Professores/Prof. Júlia - Artes(1).png",
  },
  {
    id: "cartoon-027",
    nome: "Prof. Júlia",
    nomeHeroico: "Artes em ação",
    funcao: "Professor(a) de Artes",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Artes.",
    frase: "Valoriza diferentes formas de expressão e faz da criatividade uma aprendizagem.",
    foto: "img/equipe/professores/Prof. Júlia - Artes.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Júlia, Professor(a) de Artes.",
    origemArquivo: "Professores/Prof. Júlia - Artes.png",
  },
  {
    id: "cartoon-028",
    nome: "Prof. Karla",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Aproxima leitura, escrita e diálogo para fortalecer a participação dos estudantes.",
    foto: "img/equipe/professores/Prof. Karla - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Karla, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. Karla - Língua Portuguesa.png",
  },
  {
    id: "cartoon-029",
    nome: "Prof. Leudiceia",
    nomeHeroico: "Estudo Religioso em ação",
    funcao: "Professor(a) de Estudo Religioso",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Estudo Religioso.",
    frase: "Promove respeito, reflexão e convivência entre diferentes crenças e visões.",
    foto: "img/equipe/professores/Prof. Leudiceia - Estudo Religioso.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Leudiceia, Professor(a) de Estudo Religioso.",
    origemArquivo: "Professores/Prof. Leudiceia - Estudo Religioso.png",
  },
  {
    id: "cartoon-030",
    nome: "Prof. Marcus",
    nomeHeroico: "Biologia em ação",
    funcao: "Professor(a) de Biologia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Biologia.",
    frase: "Apresenta a vida como investigação, cuidado e responsabilidade com o ambiente.",
    foto: "img/equipe/professores/Prof. Marcus - Biologia(1).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Marcus, Professor(a) de Biologia.",
    origemArquivo: "Professores/Prof. Marcus - Biologia(1).png",
  },
  {
    id: "cartoon-031",
    nome: "Prof. Marcus",
    nomeHeroico: "Biologia em ação",
    funcao: "Professor(a) de Biologia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Biologia.",
    frase: "Relaciona corpo, natureza e ciência para ampliar o cuidado com a vida.",
    foto: "img/equipe/professores/Prof. Marcus - Biologia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Marcus, Professor(a) de Biologia.",
    origemArquivo: "Professores/Prof. Marcus - Biologia.png",
  },
  {
    id: "cartoon-032",
    nome: "Prof. Marcus",
    nomeHeroico: "Geografia em ação",
    funcao: "Professor(a) de Geografia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Mostra como sociedade e espaço se transformam por escolhas coletivas.",
    foto: "img/equipe/professores/Prof. Marcus - Geografia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Marcus, Professor(a) de Geografia.",
    origemArquivo: "Professores/Prof. Marcus - Geografia.png",
  },
  {
    id: "cartoon-033",
    nome: "Prof. Marlúcia",
    nomeHeroico: "Língua Portuguesa em ação",
    funcao: "Professor(a) de Língua Portuguesa",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Língua Portuguesa.",
    frase: "Incentiva cada estudante a ler o mundo e escrever sua própria trajetória.",
    foto: "img/equipe/professores/Prof. Marlúcia - Língua Portuguesa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Marlúcia, Professor(a) de Língua Portuguesa.",
    origemArquivo: "Professores/Prof. Marlúcia - Língua Portuguesa.png",
  },
  {
    id: "cartoon-034",
    nome: "Prof. Ozias",
    nomeHeroico: "Sociologia em ação",
    funcao: "Professor(a) de Sociologia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Sociologia.",
    frase: "Conecta sociedade e cotidiano para estimular pensamento crítico e participação.",
    foto: "img/equipe/professores/Prof. Ozias - Sociologia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Ozias, Professor(a) de Sociologia.",
    origemArquivo: "Professores/Prof. Ozias - Sociologia.png",
  },
  {
    id: "cartoon-035",
    nome: "Prof. Reinaldo",
    nomeHeroico: "Matemática em ação",
    funcao: "Professor(a) de Matemática",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Usa a Matemática para transformar desafios em raciocínio, autonomia e possibilidades.",
    foto: "img/equipe/professores/Prof. Reinaldo - Matemática.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Reinaldo, Professor(a) de Matemática.",
    origemArquivo: "Professores/Prof. Reinaldo - Matemática.png",
  },
  {
    id: "cartoon-036",
    nome: "Prof. Roberto",
    nomeHeroico: "Geografia em ação",
    funcao: "Professor(a) de Geografia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Geografia.",
    frase: "Explora mapas e territórios para compreender as relações que movem a sociedade.",
    foto: "img/equipe/professores/Prof. Roberto - Geografia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Roberto, Professor(a) de Geografia.",
    origemArquivo: "Professores/Prof. Roberto - Geografia.png",
  },
  {
    id: "cartoon-037",
    nome: "Prof. Roberto Cunha",
    nomeHeroico: "Matemática em ação",
    funcao: "Professor(a) de Matemática",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Matemática.",
    frase: "Constrói caminhos de raciocínio para que os números façam sentido no cotidiano.",
    foto: "img/equipe/professores/Prof. Roberto Cunha - Matemática.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Roberto Cunha, Professor(a) de Matemática.",
    origemArquivo: "Professores/Prof. Roberto Cunha - Matemática.png",
  },
  {
    id: "cartoon-038",
    nome: "Prof. Said",
    nomeHeroico: "Física em ação",
    funcao: "Professor(a) de Física",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Física.",
    frase: "Desperta a curiosidade sobre a matéria, a energia e os fenômenos do dia a dia.",
    foto: "img/equipe/professores/Prof. Said - Física.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Said, Professor(a) de Física.",
    origemArquivo: "Professores/Prof. Said - Física.png",
  },
  {
    id: "cartoon-039",
    nome: "Prof. Teresinha",
    nomeHeroico: "Biologia em ação",
    funcao: "Professor(a) de Biologia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Biologia.",
    frase: "Faz da Biologia uma lente para observar, questionar e proteger a vida.",
    foto: "img/equipe/professores/Prof. Teresinha - Biologia(1).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Teresinha, Professor(a) de Biologia.",
    origemArquivo: "Professores/Prof. Teresinha - Biologia(1).png",
  },
  {
    id: "cartoon-040",
    nome: "Prof. Teresinha",
    nomeHeroico: "Biologia em ação",
    funcao: "Professor(a) de Biologia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Biologia.",
    frase: "Relaciona ciência e cotidiano para cultivar escolhas mais conscientes.",
    foto: "img/equipe/professores/Prof. Teresinha - Biologia(2).jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Teresinha, Professor(a) de Biologia.",
    origemArquivo: "Professores/Prof. Teresinha - Biologia(2).png",
  },
  {
    id: "cartoon-041",
    nome: "Prof. Teresinha",
    nomeHeroico: "Biologia em ação",
    funcao: "Professor(a) de Biologia",
    categoria: "professores",
    setor: "Equipe docente",
    contribuicao: "Contribui para a aprendizagem na área de Biologia.",
    frase: "Conduz descobertas sobre os seres vivos com curiosidade e responsabilidade.",
    foto: "img/equipe/professores/Prof. Teresinha - Biologia.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Prof. Teresinha, Professor(a) de Biologia.",
    origemArquivo: "Professores/Prof. Teresinha - Biologia.png",
  },
  {
    id: "cartoon-043",
    nome: "Seu Eduardo",
    nomeHeroico: "Acolhimento e cuidado",
    funcao: "Portaria",
    categoria: "apoio",
    setor: "Portaria",
    contribuicao: "Cuida do acolhimento, do acesso e da rotina escolar.",
    frase: "Recebe, orienta e ajuda a manter a entrada da escola acolhedora e organizada.",
    foto: "img/equipe/portaria/Seu Eduardo.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Seu Eduardo, Portaria.",
    origemArquivo: "Portaria/Seu Eduardo.png",
  },
  {
    id: "cartoon-044",
    nome: "Arlindo",
    nomeHeroico: "Equipe em ação",
    funcao: "Função a confirmar",
    categoria: "outros",
    setor: "Departamento a confirmar",
    contribuicao: "Integra a rede de trabalho que mantém a escola em movimento.",
    frase: "Contribui com presença e compromisso para que a rotina da escola siga em movimento.",
    foto: "img/equipe/outros/Arlindo.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Arlindo, Função a confirmar.",
    origemArquivo: "Outros/Arlindo.png",
  },
  {
    id: "cartoon-045",
    nome: "Camila",
    nomeHeroico: "Equipe em ação",
    funcao: "Função a confirmar",
    categoria: "outros",
    setor: "Departamento a confirmar",
    contribuicao: "Integra a rede de trabalho que mantém a escola em movimento.",
    frase: "Soma cuidado e colaboração às tarefas que sustentam o dia a dia escolar.",
    foto: "img/equipe/outros/Camila.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Camila, Função a confirmar.",
    origemArquivo: "Outros/Camila.png",
  },
  {
    id: "cartoon-046",
    nome: "Cley",
    nomeHeroico: "Equipe em ação",
    funcao: "Função a confirmar",
    categoria: "outros",
    setor: "Departamento a confirmar",
    contribuicao: "Integra a rede de trabalho que mantém a escola em movimento.",
    frase: "Ajuda a transformar necessidades da escola em ações de apoio e cooperação.",
    foto: "img/equipe/outros/Cley.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Cley, Função a confirmar.",
    origemArquivo: "Outros/Cley.png",
  },
  {
    id: "cartoon-047",
    nome: "Elisa",
    nomeHeroico: "Equipe em ação",
    funcao: "Função a confirmar",
    categoria: "outros",
    setor: "Departamento a confirmar",
    contribuicao: "Integra a rede de trabalho que mantém a escola em movimento.",
    frase: "Participa da rede de cuidados que acolhe pessoas e fortalece a convivência.",
    foto: "img/equipe/outros/Elisa.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Elisa, Função a confirmar.",
    origemArquivo: "Outros/Elisa.png",
  },
  {
    id: "cartoon-048",
    nome: "Joilton",
    nomeHeroico: "Equipe em ação",
    funcao: "Função a confirmar",
    categoria: "outros",
    setor: "Departamento a confirmar",
    contribuicao: "Integra a rede de trabalho que mantém a escola em movimento.",
    frase: "Colabora nos bastidores para que estudantes e profissionais encontrem uma escola funcionando.",
    foto: "img/equipe/outros/Joilton.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Joilton, Função a confirmar.",
    origemArquivo: "Outros/Joilton.png",
  },
  {
    id: "cartoon-049",
    nome: "Simone",
    nomeHeroico: "Equipe em ação",
    funcao: "Função a confirmar",
    categoria: "outros",
    setor: "Departamento a confirmar",
    contribuicao: "Integra a rede de trabalho que mantém a escola em movimento.",
    frase: "Acrescenta atenção e responsabilidade ao trabalho coletivo que faz a escola acontecer.",
    foto: "img/equipe/outros/Simone.jpg",
    textoAlternativo: "Ilustração em estilo cartoon de Simone, Função a confirmar.",
    origemArquivo: "Outros/Simone.png",
  },
];
